### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by liuyuyan6100** [open-v2x/dandelion#240]
## Describe the bug

系统环境问题，在搭建Dandelion环境时，按照文档操作出现文件缺失的问题

## To Reproduce

1. 严格按照《分分钟搞定 OpenV2X 开发环境 - Beihai 版本》的操作执行，系统环境为ubuntu22.04
2. 在《Dandelion 路侧设备管理模块》执行到uvicorn --reload --reload-dir dandelion --port 28300 --log-level debug dandelion.main:app --host 0.0.0.0时出现报错

## Expected behavior

期待按照操作能够正常编译

## Screenshots

![image](https://github.com/open-v2x/dandelion/assets/35398244/530126eb-05a6-400b-8da9-24d488057ffe)

## Log Information

打印如下：
(venv) root@lyy-virtual-machine:/home/lyy/v2x/dandelion# uvicorn --reload --reload-dir dandelion --port 28300 --log-level debug dandelion.main:app --host 0.0.0.0
INFO:     Will watch for changes in these directories: ['/home/lyy/v2x/dandelion/dandelion']
INFO:     Uvicorn running on http://0.0.0.0:28300 (Press CTRL+C to quit)
INFO:     Started reloader process [95578] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lyy/v2x/dandelion/.tox/venv/lib/python3.10/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/lyy/v2x/dandelion/.tox/venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lyy/v2x/dandelion/.tox/venv/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/lyy/v2x/dandelion/.tox/venv/lib/python3.10/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/lyy/v2x/dandelion/.tox/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lyy/v2x/dandelion/./dandelion/main.py", line 32, in <module>
    from dandelion.api.api_v1.api import api_router
  File "/home/lyy/v2x/dandelion/./dandelion/api/api_v1/api.py", line 19, in <module>
    from dandelion.api.api_v1.endpoints import (
  File "/home/lyy/v2x/dandelion/./dandelion/api/api_v1/endpoints/edge_site.py", line 34, in <module>
    PORT = deps.get_gunicorn_port()
  File "/home/lyy/v2x/dandelion/./dandelion/api/deps.py", line 180, in get_gunicorn_port
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/etc/dandelion/gunicorn.py'

## Desktop (please complete the following information):

- OS: [ubuntu 22.04]
- Browser [chrome]

**Comment by wu-wenxiang** [comment]
https://openv2x.net/posts/2023-04-03-1/
